# Change these first
owner: Ze0l # Your GitHub organization or username, where this repository lives
repo: VortexStatus # The name of this repository

sites:
  - name: Playvortex
    url: https://playvortex.io
    maxResponseTime: 5000
    skipDeleteIssues: true
    
status-website:
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: 
  baseUrl: /VortexStatus
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Vortex Status
  introTitle: "test"
  introMessage: Test
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
